site_name: IHC Grupo 9

theme: 
  name: material
  language: pt
  features:
    - navigation.instant
  palette:
    primary: indigo
    accent: indigo

nav:
  - Início: index.md
  - Planejamento: planejamento.md
  - Processo de Design:
    - Usabilidade de Mayhew: processoDeDesign/usabilidadeDeMayhew.md
  - Análise de Requisitos:
    - Análise Hierárquica de Tarefas: analiseRequisitos/analiseHierarquicaTarefas.md
